music_pos = 0;
play = false;
global.leveltorestart = -4;
instance_destroy(obj_pigtotal);

music_arr = [
	["event:/soundtest/base/intro", "Time For A Smackdown - MrSauceman"],
	["event:/soundtest/base/pizzadeluxe", "Pizza Deluxe - PostElvis"],
	["event:/soundtest/base/funiculi", "funiculi funicula - ClascyJitto"],
	["event:/soundtest/base/pizzatime", "It's Pizza Time! - MrSauceman"],
	["event:/soundtest/base/lap", "The Death That I Deservioli - MrSauceman"],
	["event:/soundtest/base/mondays", "Mondays - MrSauceman"],
	["event:/soundtest/base/unearthly", "Unearthly Blues - MrSauceman"],
	["event:/soundtest/base/hotspaghetti", "Hot Spaghetti - MrSauceman"],
	["event:/soundtest/base/coldspaghetti", "Cold Spaghetti - MrSauceman"],
	["event:/soundtest/base/theatrical", "Theatrical Shenanigans - MrSauceman"],
	["event:/soundtest/base/putonashow", "Put On A Show!! - ClascyJitto"],
	["event:/soundtest/base/dungeon", "Dungeon Freakshow - ClascyJitto"],
	["event:/soundtest/base/pepperman", "Pepperman Strikes! - MrSauceman"],
	["event:/soundtest/base/tuesdays", "Tuesdays - MrSauceman"],
	["event:/soundtest/base/oregano", "Oregano Desert - ClascyJitto"],
	["event:/soundtest/base/ufo", "Oregano UFO - ClascyJitto"],
	["event:/soundtest/base/tombstone", "Tombstone Arizona - MrSauceman"],
	["event:/soundtest/base/mort", "Mort's Farm - ClascyJitto"],
	["event:/soundtest/base/kidsmenu", "What's On The Kid's Menu? - ClascyJitto"],
	["event:/soundtest/base/yeehaw", "Yeehaw Deliveryboy - ClascyJitto"],
	["event:/soundtest/base/vigilante", "Calzonification - MrSauceman"],
	["event:/soundtest/base/wednesdays", "Wednesdays - ClascyJitto"],
	["event:/soundtest/base/tropical", "Tropical Crust - MrSauceman"],
	["event:/soundtest/base/forest1", "mmm yess put the tree on my pizza - ClascyJitto"],
	["event:/soundtest/base/gustavo", "gustavo - ClascyJitto"],
	["event:/soundtest/base/forest2", "Wudpecker - ClascyJitto"],
	["event:/soundtest/base/goodeatin", "Good Eatin' - ClascyJitto"],
	["event:/soundtest/base/extraterrestial", "Extraterrestial Wahwahs - MrSauceman"],
	["event:/soundtest/base/noise", "Pimpin' Hot Stuff - MrSauceman"],
	["event:/soundtest/base/thursdays", "Thursdays - ClascyJitto"],
	["event:/soundtest/base/tubular", "Tubular Trash Zone - MrSauceman"],
	["event:/soundtest/base/engineer", "Pizza Engineer - MrSauceman"],
	["event:/soundtest/base/saucemachine", "Peppino's Sauce Machine - MrSauceman"],
	["event:/soundtest/base/bitethecrust", "Bite The Crust - MrSauceman"],
	["event:/soundtest/base/wayoftheitalian", "Way of the Italian - MrSauceman"],
	["event:/soundtest/base/preheat", "dont preheat your oven - ClascyJitto"],
	["event:/soundtest/base/celsius", "Celsius Troubles - ClascyJitto"],
	["event:/soundtest/base/plains", "On the Rocks - MrSauceman"],
	["event:/soundtest/base/fakepep", "Pizza Time Never Ends!! - ClascyJitto"],
	["event:/soundtest/base/fridays", "Fridays - MrSauceman"],
	["event:/soundtest/base/chateau", "There's A Bone In My Spaghetti! - MrSauceman"],
	["event:/soundtest/base/tunnely", "Tunnely Shimbers - MrSauceman"],
	["event:/soundtest/base/thousand", "Thousand March - MrSauceman"],
	["event:/soundtest/base/unexpectancy1", "Unexpectancy, Part 1 - MrSauceman"],
	["event:/soundtest/base/unexpectancy2", "Unexpectancy, Part 2 - MrSauceman"],
	["event:/soundtest/base/unexpectancy3", "Unexpectancy, Part 3 - MrSauceman"],
	["event:/soundtest/base/bye", "Bye Bye There! - MrSauceman"],
	["event:/soundtest/base/notime", "Receding Hairline Celebration Party - MrSauceman"],
	["event:/soundtest/base/meatphobia", "Meatphobia - MrSauceman"],
	["event:/soundtest/base/mayhem", "Pizza Mayhem Instrumental - MrSauceman"],
	["event:/soundtest/base/mayhem2", "Pizza Mayhem - MrSauceman"],
	["event:/music/w1/entrancesecret", "An Entrance Secret - ClascyJitto"],
	["event:/music/w1/medievalsecret", "A Medieval Secret - ClascyJitto"],
	["event:/music/w1/dungeonsecret", "A Dungeon Secret - ClascyJitto"],
	["event:/music/w1/ruinsecret", "A Ruin Secret - ClascyJitto"],
	["event:/music/w2/desertsecret", "A Desert Secret - ClascyJitto"],
	["event:/music/w2/farmsecret", "A Farm Secret - ClascyJitto"],
	["event:/music/w2/graveyardsecret", "An Undead Secret - ClascyJitto"],
	["event:/music/w2/saloonsecret", "A Saloon Secret - ClascyJitto"],
	["event:/music/w3/beachsecret", "A Secret in the Sands - ClascyJitto"],
	["event:/music/w3/forestsecret", "A Secret in the Trees - ClascyJitto"],
	["event:/music/w3/golfsecret", "A Secret Hole in One - ClascyJitto"],
	["event:/music/w3/spacesecret", "An Space Secret - ClascyJitto"],
	["event:/music/w4/freezersecret", "A Frozen Secret - ClascyJitto"],
	["event:/music/w4/industrialsecret", "An Industry Secret - ClascyJitto"],
	["event:/music/w4/sewersecret", "A Sewer Secret - ClascyJitto"],
	["event:/music/w4/streetsecret", "A Secret In The Streets - ClascyJitto"],
	["event:/music/w5/kidspartysecret", "A Secret You Don't Want To Find - ClascyJitto"],
	["event:/music/w5/warsecret", "A War Secret - ClascyJitto"],
	["event:/soundtest/base/secretworld", "Secret Lockin' - ClascyJitto"],
	["event:/soundtest/base/halloweenpause", "Spacey Pumpkins - MrSauceman"],
	["event:/soundtest/base/halloweenstart", "The Bone Rattler - MrSauceman"],
	["event:/soundtest/base/halloweenrace", "The Runner - PostElvis"]
];
if (obj_player1.character == "N" || global.swapmode)
{
	music_arr = [
		["event:/soundtest/base/entrancenoise", "The Noise's Jam-Packed Radical Anthem - MrSauceman"],
		["event:/soundtest/base/doise", "Impasta Syndrome - MrSauceman"],
		["event:/soundtest/base/pizzatimenoise", "Distasteful Anchovi - ClascyJitto"],
		["event:/soundtest/base/lap2noise", "World Wide Noise - ClascyJitto"],
		["event:/soundtest/base/pizzaheadnoise", "Unexpectancy, Part 3 (Remix) - ClascyJitto"],
		["event:/soundtest/base/noisefinalescape", "I Need A Noise - MrSauceman"],
		["event:/soundtest/base/creditsnoise", "New Noise Resolutionz - ClascyJitto"]
	];
}
index = 0;
music_event = fmod_event_create_instance(music_arr[0][0]);
